const $=id=>document.getElementById(id); const API_BASE=(window.STUDY_PLANNER_API_URL||'').replace(/\/$/,''); let config=null; let cached={agenda:null,tasks:null};
async function api(path,opts={}){const r=await fetch(API_BASE+path,{credentials:'include',headers:{'Content-Type':'application/json',...(opts.headers||{})},...opts});if(r.status===401)showLogin();if(!r.ok)throw Error((await r.json()).detail||'Request failed');return r.json()}
function showLogin(){ $('login').hidden=false;$('planner').hidden=true }
function showPlanner(){ $('login').hidden=true;$('planner').hidden=false }
function setStatus(text){$('status').textContent=text}
function renderAgenda(data){cached.agenda=data;$('today').textContent=data.date; $('agenda-list').innerHTML=data.items.map(x=>`<article class="item ${data.current&&data.current.id===x.id?'current':''}"><div class="time">${x.start_time}–${x.end_time}</div><div>${x.title}</div><small class="muted">${x.category}${x.status==='completed'?' · Completed':''}</small></article>`).join('')||'<p>No agenda items.</p>'}
function renderTasks(data){cached.tasks=data.tasks;$('task-list').innerHTML=data.tasks.map(t=>`<article class="task"><div><div>${t.title}</div><small class="muted">${t.column_name}${t.due_date?' · Due '+t.due_date+' '+(t.due_time||''):''}</small></div><button data-complete="${t.id}">${t.column_name==='Completed'?'Reopen':'Complete'}</button></article>`).join('')||'<p>No tasks yet.</p>';document.querySelectorAll('[data-complete]').forEach(b=>b.onclick=async()=>{const t=data.tasks.find(x=>x.id==b.dataset.complete);await api('/api/tasks/'+t.id,{method:'PATCH',body:JSON.stringify({column:t.column_name==='Completed'?'In Progress':'Completed'})});load()})}
async function load(){try{showPlanner();renderAgenda(await api('/api/agenda'));renderTasks(await api('/api/tasks'));setStatus('')}catch(e){setStatus('Offline or unavailable. Showing the last saved view.');if(cached.agenda)renderAgenda(cached.agenda);if(cached.tasks)renderTasks({tasks:cached.tasks})}}
async function enablePush(){try{if(!('serviceWorker'in navigator)||!('PushManager'in window))throw Error('Web Push is not supported');config=config||await api('/api/config');if(!config.vapid_public_key)throw Error('Push is not configured on the server');const reg=await navigator.serviceWorker.register('/sw.js');const permission=await Notification.requestPermission();if(permission!=='granted')throw Error('Notification permission was not granted');const b64=s=>{s=s.replace(/-/g,'+').replace(/_/g,'/');s+='='.repeat((4-s.length%4)%4);return Uint8Array.from(atob(s),c=>c.charCodeAt(0))};const sub=await reg.pushManager.subscribe({userVisibleOnly:true,applicationServerKey:b64(config.vapid_public_key)});await api('/api/push/subscribe',{method:'POST',body:JSON.stringify(sub)});$('notify').textContent='Notifications enabled';setStatus('Push notifications enabled.')}catch(e){setStatus(e.message)}}
$('login-form').onsubmit=async e=>{e.preventDefault();try{await api('/auth/login',{method:'POST',body:JSON.stringify({username:$('username').value,password:$('password').value})});await load()}catch(e){$('login-error').textContent=e.message}};
$('logout').onclick=async()=>{await api('/auth/logout',{method:'POST'});showLogin()};$('notify').onclick=enablePush;$('task-form').onsubmit=async e=>{e.preventDefault();await api('/api/tasks',{method:'POST',body:JSON.stringify({title:$('task-title').value})});$('task-title').value='';load()};document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('agenda').hidden=b.dataset.tab!=='agenda';$('tasks').hidden=b.dataset.tab!=='tasks'});if('serviceWorker'in navigator)navigator.serviceWorker.register('/sw.js');api('/api/config').then(()=>load()).catch(()=>showLogin());
